### ISSUE TITLE
Stub API calls

### ISSUE THREAD

**Issue by itsdn** [caseyscarborough/omdbapi#6]
- Internet connection is required to run a test suite.
- Tests are slow
- Results are fetched from OMDB every time tests are run, a lot of unnecessary load for OMDB servers

I can submit a pull request if you want.

**Comment by caseyscarborough** [comment]
That would be great, I'd gladly accept a pull request for this.

**Comment by itsdn** [comment]
@caseyscarborough Implemented in #8.
